on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew build
      - name: Upload Fabric artifact
        uses: actions/upload-artifact@v7
        with:
          name: Fabric
          path: fabric/build/libs/SmoothCoasters-Fabric-*.jar
          archive: 'false'
      - name: Upload NeoForge artifact
        uses: actions/upload-artifact@v7
        with:
          name: Fabric
          path: neoforge/build/libs/SmoothCoasters-NeoForge-*.jar
          archive: 'false'
      - name: Update description
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: ./gradlew modrinthSyncBody
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      - name: Create release
        if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          files: |
            fabric/build/libs/SmoothCoasters-Fabric-*.jar
            neoforge/build/libs/SmoothCoasters-NeoForge-*.jar
      - name: Publish
        if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
        run: ./gradlew modrinth publishCurseForge
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
